# Generated by Django 5.1 on 2024-09-01 19:25

import my_first_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='name',
            field=models.ForeignKey(on_delete=my_first_app.models.a, to='my_first_app.webpage'),
        ),
    ]
